name: flame_hooks_test
description: "Tests for the flame_hooks package."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  flame: ^1.18.0
  flame_hooks:
    path: ../
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_gen: ^5.5.0+1
dev_dependencies:
  build_runner: ^2.4.11
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  storybook_flutter: ^0.14.0
  storybook_flutter_test: any
flutter:
  uses-material-design: true
