name: flame_fuse
description: Functional behavior composition for Flame components.
version: 2.0.0
homepage: https://github.com/misha/flame_fuse
environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flame: ^1.36.0
  flutter:
    sdk: flutter
dev_dependencies:
  flame_lint: ^1.4.3
  flutter_lints: ^6.0.0
