name: flame_hooks
description: "Hook implementation for the Flame game engine."
version: 0.0.1
homepage: https://github.com/misha/flame_hooks
environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flame_lint: ^1.2.0
