name: flame_fuse
description: Functional behavior composition for Flame components.
version: 3.0.0
homepage: https://github.com/misha/flame_fuse
environment:
  sdk: ^3.11.1
  flutter: ">=3.41.4"
dependencies:
  flame: ^1.36.0
  flutter:
    sdk: flutter
dev_dependencies:
  flame_lint: ^1.4.3
  flutter_lints: ^6.0.0
