name: fuse
description: "Functional behavior composition for Flame components."
version: 1.0.0
homepage: https://github.com/misha/fuse
environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"
dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter
dev_dependencies:
  flame_lint: ^1.2.0
  flutter_lints: ^3.0.0
