name: fuse_test
description: "Tests for the fuse package."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.1 <4.0.0"
dev_dependencies:
  build_runner: ^2.4.11
  flame: ^1.18.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.5.0+1
  flutter_hooks: ^0.20.5
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  fuse:
    path: ../
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  storybook_flutter: ^0.14.0
  storybook_flutter_test: any
flutter:
  uses-material-design: true
